title: "Ultron"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true

aux_links:
  "Marvel Infinity Discord Server":
    - "//discord.gg/marvelinfinity"

logo: "/assets/ultron.png"
