title: "Ultron"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true

aux_links:
  "Marvel Infinity Discord Server":
    - "//discord.gg/marvelinfinity"
aux_links_new_tab: true

logo: "/assets/ultron.png"
